version: '3'
services:
  api:
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backbone
    environment:
      - USE_ENV=true
      - DATABASE=mongodb://mongo:27017/myapp
      - REDIS_URL=localhost
      - REDIS_PORT=6379
      - JWT_SECRET=some_superSecret_secret
      - JWT_VALID_MIN=120
      - LOG_LEVEL=info
    depends_on:
      - mongo
      - redis
    build:
      context: ./api

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - backbone
    volumes:
      - ./data:/data/db:delegated
      - ./backups:/data/backups:delegated

  redis:
      container_name: redis
      image: redis
      networks:
        - backbone
  app:
    container_name: app_nginx
    restart: always
    build: ./
    networks:
      - backbone
    ports:
      - "8000:8000"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8000
    #command: ['cat', '/etc/nginx/nginx.conf']
    command: /bin/bash -c "/etc/nginx/run_nginx.sh"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf

networks:
  backbone:
    driver: bridge
